development:
  adapter: postgresql
  encoding: unicode
  database: cranio_development
  pool: 5
  username: marenwoodruff
  password: cranio


test:
  adapter: postgresql
  encoding: unicode
  database: cranio_test
  pool: 5
  username: marenwoodruff 
  password: cranio

production:
  adapter: postgresql
  encoding: unicode
  database: cranio_development
  pool: 5
  username: marenwoodruff
  password: cranio